### ISSUE TITLE
Set cookies to remember volume and hide/show text option

### ISSUE THREAD

**Issue by josephfusco** [snowyescape/snowyescape#5]
<img width="937" alt="screen shot 2016-10-01 at 10 27 29 pm" src="https://cloud.githubusercontent.com/assets/6676674/19018181/53b098c2-8826-11e6-971f-c06512473542.png">

**Comment by arijitAD** [comment]
I would like to work on this.

**Comment by josephfusco** [comment]
@arijitAD go for it!

**Comment by arijitAD** [comment]
Thank you.. Will send a PR by tomorrow..

**Comment by josephfusco** [comment]
Fixed with #10
